name: miner

channels:
  - defaults  # Add more channels if needed
  - conda-forge/noarch
  - conda-forge/linux-64
  - pytorch/linux-64                 
  - pytorch/noarch
  - nvidia/linux-64
  - nvidia/noarch
  - bioconda

dependencies:
  - python=3.10  
  - numpy       
  - pandas      
  - matplotlib  
  - biopython
  - open3d
  - scipy
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - mmseq

 
pip:
  - tmtools
  - jax[cpu]
  - git+https://github.com/deepmind/dm-haiku
  - fair-esm
