args:
  base_scannet_path: /home/iscb/wolfson/hagairavid/scannet_atom_types
  df_path: datasets/csv_files/homology_25_10/val.csv
  esm_layer: 18
  esm_model: esm2_t30_150M_UR50D
  max_cath: 4
  max_length: 5000
  seed: 81
  use_esm: true
name: ScanNetDataset
