trainer:
  exp_name: only-recycling0-ligandrmsd5-400-100-remove-invalid-esm30
  tags: ["atom", "esm", "homology_split"]
  max_epochs: 10
  validate_only: false
  check_val_every_n_epoch: 1
  gradient_clipping: 30
  # profiler: true
  # ckpt_path: "checkpoints/split7-10gnn-recycling2-lambda05/epoch=29-step=76440.ckpt"
model:
  name: LocAlign
  args:
    n_iter_recycling: 0
    corr_rmsd_lambda: 0.1
    embedding_cosine_lambda: 1.0
    gap_lambda: 1.00
    ligaud_rmsd_lambda: 5.0
    input_layer:
      name: 
        EmbeddingBlock
      args:
        n_blocks: 3
        input_dim: 1004
        hidden_dim: 256
        output_dim: 256
        dropout: 0.1
        norm_in_last_layer: true
    denoiser:
      name: 
        CDM
      args:
        n_nodes: 100
        n_gnn_layers: 10
        n_rbf_functions: 32
        with_angles: true
    keypoints_selection:
      name: KeypointsSelection
      args:
        embedding_size: 256
        n_rbf_functions: 16
        top_k: 400
    loss:
      use_transformation: false
      pocket:
        name: PocketLoss
        args: {"return_non_linear": True}
      ligand:
        name: LigandLoss
        args: {}
      transformation:
        name: RTLoss
        args: {"translation_weight": 0.1}
    optimizer:
      name: Adam
      args:
        learning_rate: 0.0002
        scheduler:
          name: OneCycleLR
          interval: step
          args:

            max_lr: 0.0002
            epochs: 10
            steps_per_epoch: 8712
            div_factor: 25
            # final_div_factor: 1e4

dataset:
  train:
    name: ScanNetDataset
    args:
      df_path: datasets/csv_files/homology_25_10/train.csv
      base_embedding_path: '/home/iscb/wolfson/hagairavid/scannet_outputs_knn_25_10_2025'
      esm_model: "esm2_t30_150M_UR50D"
      use_esm: true
      esm_layer: 30
      # n_samples: 30
      seed: 41
      # min_cath: 3
      max_cath: 8
      bbc_filter_ratio: 20
      max_length: 2000
  validation:
    name: ScanNetDataset
    args:
      df_path: datasets/csv_files/homology_25_10/val.csv
      base_embedding_path: '/home/iscb/wolfson/hagairavid/scannet_outputs_knn_25_10_2025'
      esm_model: "esm2_t30_150M_UR50D"
      use_esm: true
      # n_samples: 10
      esm_layer: 30
      seed: 81
      max_cath: 4
      # bbr_filter_ratio: 0.3
      max_length: 5000
dataloader:
  train_batch_size: 8
  valid_batch_size: 1
  n_workers: 12