trainer:
  exp_name: "baseline-1708-Softalign-sw"
  tags: ["baseline"]
  max_epochs: 30
  validate_only: true
  profiler: false
model:
  name: Baseline
  args:
    model_name: "SoftAlignAligner"
 
dataset:
  validation:
    name: ScannetDataset
    args:
      base_embedding_path: /home/iscb/wolfson/hagairavid/scannet_outputs
      esm_model: "esm2_t30_150M_UR50D"
      df_path: datasets/csv_files/homology_1708_05/val_baseline.csv
      seed: 81
      level: "atom"
      # n_samples: 100
      min_cath: 0
      max_cath: 4
 
dataloader:
  train_batch_size: 8
  valid_batch_size: 1
  test_batch_size: 1
  n_workers: 15