trainer:
  exp_name: "baseline-SoftAlign-homology_split"
  tags: ["baseline", "homology_split"]
  max_epochs: 30
  validate_only: true
  profiler: false
model:
  name: Baseline
  args:
    model_name: "SoftAlignAligner"
 
dataset:
  validation:
    name: ScanNetDataset
    args:
      base_scannet_path: '/home/iscb/wolfson/hagairavid/scannet_2212'
      esm_model: "esm2_t30_150M_UR50D"
      df_path: datasets/csv_files/homology_25_10/val_baseline.csv
      seed: 81
      # n_samples: 100
      min_cath: 0
      max_cath: 4
 
dataloader:
  train_batch_size: 8
  valid_batch_size: 1
  test_batch_size: 1
  n_workers: 15