trainer:
  exp_name: dp01-10gnn-3blocks-k500-bbc20
  tags: ["virtual", "atom", "grouping_1305", "1800", "new_block"]
  max_epochs: 30
  validate_only: False
  check_val_every_n_epoch: 3
  gradient_clipping: 30
  # profiler: false
  # ckpt_path: "checkpoints/denoiser-b8-k2000-5000-top1200-dp01-differentgnn5-1305/epoch=8-step=47799.ckpt"
model:
  name: VirtualSoftBB
  args:
    # plot_dir: "plots/maskedln-atom-256-pocketloss-dp002/val"
    max_iter: 1
    n_iter_train: 1
    top_k: 1200
    input_layer:
      name: 
        EmbeddingBlock
      args:
        n_blocks: 3
        input_dim: 256
        hidden_dim: 256
        output_dim: 256
        dropout: 0.1
        norm_in_last_layer: false
    virtual_layer:
      name: 
        EmbeddingBlock
      args:
        n_blocks: 3
        input_dim: 256
        output_dim: 3
        dropout: 0.1
    scalar_layer:
      name: 
        EmbeddingBlock
      args:
        n_blocks: 3
        input_dim: 256
        output_dim: 1
        bias: false
        dropout: 0.1
      
    denoiser:
      name: 
        CorrespondenceDenoisingModule
      args:
        k: 500
        n_gnn_layers: 10
        n_rbf_functions: 16
    loss:
      use_transformation: false
      pocket:
        name: PocketLoss
        args: {"return_non_linear": True}
      ligand:
        name: LigandLoss
        args: {}
      transformation:
        name: RTLoss
        args: {"translation_weight": 0.1}
    optimizer:
      name: Adam
      args:
        learning_rate: 0.0002
        scheduler:
          name: OneCycleLR
          interval: step
          args:

            max_lr: 0.0005
            epochs: 30
            steps_per_epoch: 2755      # epochs × steps_per_epoch
            div_factor: 25
            # final_div_factor: 1e4

dataset:
  train:
    name: ScannetDataset
    args:
      df_path: aligner_dl/datasets/csv_files/grouping_1305/train.csv
      # n_samples: 10
      seed: 41
      # min_cath: 4
      max_cath: 8
      bbc_filter_ratio: 20
      level: "atom"
      max_length: 5000
  validation:
    name: ScannetDataset
    args:
      df_path: aligner_dl/datasets/csv_files/grouping_1305/val.csv
      # n_samples: 15
      seed: 81
      max_cath: 4
      # bbr_filter_ratio: 0.3
      level: "atom"
      max_length: 5000
dataloader:
  train_batch_size: 8
  valid_batch_size: 1
  n_workers: 12