trainer:
  exp_name: "maskedln-dp000-l2-up-to-4"
  tags: ["virtual", "atom", "grouping_1302", "1200", "new_block"]
  max_epochs: 15
  validate_only: false
  check_val_every_n_epoch: 5
  gradient_clipping: 15
  # profiler: false
  # ckpt_path: "checkpoints/denoiser-b4-k1000-1800-upto4cath-upto5dist-fix-eps-lr0005/epoch=19-step=96680.ckpt"
model:
  name: VirtualSoftBB
  args:
    # plot_dir: "plots/maskedln-atom-256-pocketloss-dp002/val"
    max_iter: 5
    n_iter_train: 2
    input_layer:
      name: 
        EmbeddingBlock
      args:
        n_blocks: 3
        input_dim: 256
        hidden_dim: 256
        output_dim: 256
        dropout: 0.0
        norm_in_last_layer: false
    virtual_layer:
      name: 
        EmbeddingBlock
      args:
        n_blocks: 1
        input_dim: 256
        output_dim: 3
    scalar_layer:
      name: 
        EmbeddingBlock
      args:
        n_blocks: 1
        input_dim: 256
        output_dim: 1
        bias: false
      
    denoiser:
      name: 
        CorrespondenceDenoisingModule
      args:
        k: 1000
    loss:
      use_transformation: false
      pocket:
        name: PocketLoss
        args: {"return_non_linear": True}
      ligand:
        name: LigandLoss
        args: {}
      transformation:
        name: RTLoss
        args: {"translation_weight": 0.1}
    optimizer:
      name: Adam
      args:
        learning_rate: 0.0005

dataset:
  train:
    name: ScannetDataset
    args:
      df_path: aligner_dl/datasets/csv_files/grouping_1302/train.csv
      # n_samples: 10
      seed: 41
      max_cath: 4
      bbr_filter_ratio: 0.3
      level: "atom"
      max_length: 1800
  validation:
    name: ScannetDataset
    args:
      df_path: aligner_dl/datasets/csv_files/grouping_1302/val.csv
      # n_samples: 15
      seed: 81
      max_cath: 4
      bbr_filter_ratio: 0.3
      level: "atom"
      max_length: 5000
dataloader:
  train_batch_size: 4
  valid_batch_size: 1
  n_workers: 12