trainer:
  exp_name: "skip-cath1-nonlinearrmsd"
  validate_only: false
  gradient_clipping: 10.0
model:
  name: LearnableSoftBB
  args:
    max_iter: 5
    skip_connection: True
    layers:
      name:
        FeatureBlock
      args:
        n_blocks: 3
        input_dim: 128
        hidden_dim: 128
        output_dim: 128
    loss:
      pocket:
        name: PocketLoss
        args: {"return_non_linear": False}
      # transformation:
      #   name: RTLoss
      #   args: {}
    optimizer:
      name: Adam
      args:
        learning_rate: 0.001
dataset:
  train:
    name: ScannetDataset
    args:
      df_path: datasets/csv_files/no_grouping/train.csv
      # n_samples: 100
      seed: 81
      min_cath: 3
  validation:
    name: ScannetDataset
    args:
      df_path: datasets/csv_files/no_grouping/val.csv
      seed: 81
      # n_samples: 100
      min_cath: 1
  test:
    name: ScannetDataset
    args:
      df_path: datasets/csv_files/no_grouping/test.csv
      seed: 81
      min_cath: 1
dataloader:
  train_batch_size: 8
  valid_batch_size: 1
  test_batch_size: 1