trainer:
  exp_name: "delete-test-all-changes-val-batch1"
  max_epochs: 30
  validate_only: false
  check_val_every_n_epoch: 1
  gradient_clipping: 30.0
  profiler: false
  # ckpt_path: "checkpoints/cath1-modelgpt-dropout005-withnormrelu/epoch=19-step=13040.ckpt"
  ckpt_path: null
model:
  name: LearnableSoftBB
  args:
    max_iter: 5
    layers:
      name:
        FeatureBlockGPT
      args:
        skip_connection: True
        n_blocks: 3
        input_dim: 128
        hidden_dim: 128
        output_dim: 128
        dropout: 0.05
    loss:
      pocket:
        name: PocketLoss
        args: {"return_non_linear": True}
      # transformation:
      #   name: RTLoss
      #   args: {}
    optimizer:
      name: Adam
      args:
        learning_rate: 0.001
dataset:
  train:
    name: ScannetDataset
    args:
      df_path: datasets/csv_files/no_grouping/train.csv
      # n_samples: 100
      seed: 81
      min_cath: 1
  validation:
    name: ScannetDataset
    args:
      df_path: datasets/csv_files/no_grouping/val.csv
      seed: 81
      # n_samples: 100
      min_cath: 1
  test:
    name: ScannetDataset
    args:
      df_path: datasets/csv_files/no_grouping/test.csv
      seed: 81
      min_cath: 1
dataloader:
  train_batch_size: 8
  valid_batch_size: 1
  test_batch_size: 1
  n_workers: 30