args:
  base_scannet_path: ${SCANNET_DIR}
  df_path: datasets/csv_files/ligand_25_10/test.csv
  esm_layer: 18
  esm_model: esm2_t30_150M_UR50D
  max_cath: 4
  max_length: 5000
  seed: 81
  use_esm: true
name: ScanNetDataset
